### PR TITLE
fix: 添加边框；右键菜单显示时悬浮按钮不隐藏

### PR DESCRIPTION
**Pull request by feeengli**
添加边框；右键菜单显示时悬浮按钮不隐藏

Log: 添加边框；右键菜单显示时悬浮按钮不隐藏

Bug: https://pms.uniontech.com/bug-view-168469.html
         https://pms.uniontech.com/bug-view-168401.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
