### PR TITLE
fix: 删除提示窗口显示不全问题

### PR DESCRIPTION
**Pull request by feeengli**
删除提示窗口显示不全问题修复

Log: 删除提示窗口显示不全问题修复

Bug: https://pms.uniontech.com/bug-view-185583.html

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
