### PR TITLE
fix: klv蓝牙耳机双击不播放问题

### PR DESCRIPTION
**Pull request by feeengli**
修复klv/klu蓝牙耳机暂停后无法播放问题

Log: 修复klv/klu蓝牙耳机暂停后无法播放问题

Bug: https://pms.uniontech.com/bug-view-187869.html
     https://pms.uniontech.com/bug-view-181325.html

### CODE REVIEW

**Review by pengfeixx — APPROVED** [review]
/+1

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Pull request merged**
