### PR TITLE
fix: 强制退出不保存导入的歌曲

### PR DESCRIPTION
**Pull request by feeengli**
修复强制退出不保存导入的歌曲

Log: 修复强制退出不保存导入的歌曲\

Bug: https://pms.uniontech.com/bug-view-215039.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
