### PR TITLE
fix: 休眠唤醒后进度条停滞，音乐无声音输出

### PR DESCRIPTION
**Pull request by feeengli**
修复休眠唤醒后进度条停滞，音乐无声音输出

Log: 修复休眠唤醒后进度条停滞，音乐无声音输出

Bug: https://pms.uniontech.com/bug-view-216759.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
