### PR TITLE
fix: 点击进度条会有轻微的POP音

### PR DESCRIPTION
**Pull request by feeengli**
所有平台都使用sdl播放器

Log: 修复点击进度条会有轻微的POP音问题

Bug: https://pms.uniontech.com/bug-view-175947.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Comment by myk1343** [comment]
[Fail原因] N/A
[Review结论] Pass
[是否满足commit提交规范] Y
[是否满足兼容性要求] Y
[是否满足编码规范] Y

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
