### PR TITLE
fix: 紧凑模式兼容，通过DTK宏判断

### PR DESCRIPTION
**Pull request by feeengli**
紧凑模式兼容，通过DTK宏判断

Log: 紧凑模式兼容，通过DTK宏判断

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
