### PR TITLE
fix: 修复按钮显示问题，部分控件适配主题

### PR DESCRIPTION
**Pull request by feeengli**
修复按钮显示问题，部分控件适配主题

Log: 修复按钮显示问题，部分控件适配主题

Bug: https://pms.uniontech.com/bug-view-176561.html
     https://pms.uniontech.com/bug-view-168469.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
