### PR TITLE
fix: lyric highlight position

### PR DESCRIPTION
**Pull request by kt286**
like this

截图_deepin-music_20220117183610

### CODE REVIEW

**Comment by wangyu0701** [comment]
Please upload test music for this issue

**Comment by kt286** [comment]
[天机（影视剧《风起洛阳》插曲） - 李常超 (Lao乾妈).zip](https://github.com/linuxdeepin/deepin-music/files/7923703/-.Lao.zip)

**Comment by wangyu0701** [comment]
Please upload the lyric

**Comment by kt286** [comment]
here is the lyric

[天机（影视剧《风起洛阳》插曲） - 李常超 (Lao乾妈).zip](https://github.com/linuxdeepin/deepin-music/files/7923851/-.Lao.zip)

**Comment by wangyu0701** [comment]
The wrong position of the lyrics highlight has been fixed : https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441

**Comment by kt286** [comment]
> The wrong position of the lyrics highlight has been fixed : [ccdcbe6](https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441)

this PR also fixes other issues:
1. highlight is not displayed when theme is light
2. the lyrics cannot return starting position in time when the song is switched

**Comment by wangyu0701** [comment]
> > The wrong position of the lyrics highlight has been fixed : [ccdcbe6](https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441)
> 
> This PR also fixes other issues:
> 
> 1. highlight is not displayed on light theme
> 2. the lyrics cannot return starting position in time when the songs is switched

1.Color matching needs to stay as designed
2.This modification will cause the lyrics window to display incompletely.
Modify as follows:
image
image

**Comment by kt286** [comment]
> > > The wrong position of the lyrics highlight has been fixed : [ccdcbe6](https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441)
> > 
> > 
> > This PR also fixes other issues:
> > 
> > 1. highlight is not displayed on light theme
> > 2. the lyrics cannot return starting position in time when the songs is switched
> 
> 1.Color matching needs to stay as designed 2.This modification will cause the lyrics window to display incompletely. Modify as follows: image image

You can revert the commit https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441 to try it,

**Comment by wangyu0701** [comment]
> > > > The wrong position of the lyrics highlight has been fixed : [ccdcbe6](https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441)
> > > 
> > > 
> > > This PR also fixes other issues:
> > > 
> > > 1. highlight is not displayed on light theme
> > > 2. the lyrics cannot return starting position in time when the songs is switched
> > 
> > 
> > 1.Color matching needs to stay as designed 2.This modification will cause the lyrics window to display incompletely. Modify as follows: image image
> 
> You can revert the commit [ccdcbe6](https://github.com/linuxdeepin/deepin-music/commit/ccdcbe69ae110467eb56305497ded5d94033b441) to try it,

1. The current line is too low
2. The next string is blocked
image

**Comment by kt286** [comment]
> 

I will close it and start a new PR

**Pull request closed without merging**
