### PR TITLE
fix: 深色模式下窗口未激活侧边栏的显示问题

### PR DESCRIPTION
**Pull request by wyu71**
同步歌单样式

Log: 歌单样式一致
Bug: https://pms.uniontech.com/bug-view-155745.html
/review @lzwind @myk1343 @hundundadi @feeengli

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
