### PR TITLE
fix: 关闭提示窗口bug修复

### PR DESCRIPTION
**Pull request by feeengli**
关闭提示窗口bug修复

Log: 关闭提示窗口bug修复

Bug: [pms.uniontech.com/bug-view-179189.html](https://pms.uniontech.com/bug-view-179189.html)

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
