### PR TITLE
fix: Fixed the issue that the scrollbar was blank

### PR DESCRIPTION
**Pull request by pengfeixx**
Fixed the issue that the scrollbar was blank

Bug: https://pms.uniontech.com/bug-view-273487.html
Log: Fixed the issue that the scrollbar was blank

### CODE REVIEW

**Review by rb-union — COMMENTED** [review]
leftPadding 直接移掉显示效果有影响

**Review by rb-union — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by myk1343 — APPROVED** [review]
+1

**Pull request merged**
