### PR TITLE
fix: music count label word wrap

### PR DESCRIPTION
**Pull request by kt286**
fix like this

截图_选择区域_20220123171707

### CODE REVIEW

**Comment by hualet** [comment]
Is this caused by the wrap flag or by the width of the label is not set enough?

**Comment by kt286** [comment]
> Is this caused by the wrap flag or by the width of the label is not set enough?

maybe the width of label is not set encough. but I an unsuccessful in setting a large width. so I modifed the wrap flag

**Comment by wangyu0701** [comment]
> > Is this caused by the wrap flag or by the width of the label is not set enough?
> 
> maybe the width of label is not set encough. but I am unsuccessful in setting a large width. so I modified the wrap flag

The label sets a maximum width limit. Word wrap is not reproduced by increasing the font size, please provide the following reproduction steps.

**Comment by kt286** [comment]
> > > Is this caused by the wrap flag or by the width of the label is not set enough?
> > 
> > 
> > maybe the width of label is not set encough. but I am unsuccessful in setting a large width. so I modified the wrap flag
> 
> The label sets a maximum width limit. Word wrap is not reproduced by increasing the font size, please provide the following reproduction steps.

change the system font to PingFang SC
https://blog.dsrkafuu.net/post/2020/extract-sf-pingfang/#%E5%AD%97%E4%BD%93%E4%B8%8B%E8%BD%BD

**Comment by wangyu0701** [comment]
> > > > Is this caused by the wrap flag or by the width of the label is not set enough?
> > > 
> > > 
> > > maybe the width of label is not set encough. but I am unsuccessful in setting a large width. so I modified the wrap flag
> > 
> > 
> > The label sets a maximum width limit. Word wrap is not reproduced by increasing the font size, please provide the following reproduction steps.
> 
> change the system font to PingFang SC https://blog.dsrkafuu.net/post/2020/extract-sf-pingfang/#%E5%AD%97%E4%BD%93%E4%B8%8B%E8%BD%BD

In the case of no line wrapping, it is recommended to use the elidedText function of QFontMetrics to handle strings that cannot be completely displayed.

**Comment by lzwind** [comment]
The current pipeline has not been compiled. Please submit it again. I'm very sorry for the trouble caused to you.

Note：In the case of no line wrapping, it is recommended to use the elidedText function of QFontMetrics to handle strings that cannot be completely displayed.

**Review by lzwind — APPROVED** [review]
good

**Pull request merged**
