### PR TITLE
fix: 紧凑模式1050适配

### PR DESCRIPTION
**Pull request by feeengli**
1050 dtk不支持紧凑模式

Log: 修复1050 dtk不支持紧凑模式

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
