### PR TITLE
fix: remove unnecessary properties

### PR DESCRIPTION
**Pull request by feeengli**
resubmit: fix: don't set RPATH #423

Log: remove unnecessary properties

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Comment by hundundadi** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
