### PR TITLE
fix: 紧凑模式显示问题，字体切换问题

### PR DESCRIPTION
**Pull request by feeengli**
修复紧凑模式标题栏按钮位置错位问题，切换字体后部分内容未刷新问题

Log: 修复紧凑模式标题栏按钮位置错位问题，切换字体后部分内容未刷新问题

Bug: https://pms.uniontech.com/bug-view-202829.html
     https://pms.uniontech.com/bug-view-202091.html

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
