### PR TITLE
fix: 应用获取打开文件路径

### PR DESCRIPTION
**Pull request by feeengli**
添加 WindowTitle

Log: 应用获取打开文件路径

Task: https://pms.uniontech.com/task-view-218113.html

### CODE REVIEW

**Comment by pengfeixx** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
