### PR TITLE
fix: get cover image from ID3v2 when ffmpeg can't parse

### PR DESCRIPTION
**Pull request by kt286**
get cover image from ID3v2 when ffmpeg can't parse

### CODE REVIEW

**Comment by feeengli** [comment]
@kt286 需要合入这笔修改后再提交一次，不然obs检查无法通过

**Comment by feeengli** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
