### PR TITLE
fix: pa连接失败时播放音乐崩溃

### PR DESCRIPTION
**Pull request by feeengli**
修复pa连接失败时播放音乐崩溃问题

Log: 修复pa连接失败时播放音乐崩溃问题

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
