### PR TITLE
fix: The tray icon does not change with the theme

### PR DESCRIPTION
**Pull request by student-ice**
修复托盘图标不跟随主题变化

### CODE REVIEW

**Comment by feeengli** [comment]
@student-ice  需要合入这笔修改后再提交一次，不然obs检查无法通过。https://github.com/linuxdeepin/deepin-music/pull/443

**Comment by student-ice** [comment]
@feeengli rebase了

**Comment by feeengli** [comment]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
