### PR TITLE
feat: adapt to new models

### PR DESCRIPTION
**Pull request by feeengli**
adapt to new models

Log: adapt to new models

### CODE REVIEW

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] y
[是否满足commit提交规范] y
[是否满足编码规范] y
[review结论] pass
[fail原因] n/a

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
