### PR TITLE
feat: 适配紧凑模式

### PR DESCRIPTION
**Pull request by feeengli**
适配紧凑模式

Log: 适配紧凑模式

Task: https://pms.uniontech.com/task-view-292057.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by rb-union** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
