### PR TITLE
Added snap development support

### PR DESCRIPTION
**Pull request by liu-xiao-guo**
In order to build the application, just need to:
- Setup the development environment for snap development according to https://snapcraft.io/
- type "snapcraft" command in the root directory of the project
- install the .snap file by using "sudo snap install *.snap --dangerous"

The final .snap file can be running in different linux distros like:
- archilinux
- opensuse
- fedora
- gentoo
- ...

### CODE REVIEW

**Comment by Iceyer** [comment]
@liu-xiao-guo 我们准备在DtkCore中封装一下Snap的路径，现在Snap是通过SNAP的环境变量来判断当前环境是snap还是通过编译宏来生成不同的代码的？现在snap会重新编译依赖库吗？

**Comment by liu-xiao-guo** [comment]
我的做法是通过宏 liu-xiao-guo/deepin-voice-recorder
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
liu-xiao-guo/deepin-voice-recorder
 deepin-voice-recorder - Voice recorder application for deepin  |   |

  |

  |

 
 

    On Friday, July 28, 2017 5:50 PM, Iceyer <notifications@github.com> wrote:
 

 @liu-xiao-guo 我们准备在DtkCore中封装一下Snap的路径，现在Snap是通过SNAP的环境变量来判断当前环境是snap还是通过编译宏来生成不同的代码的？现在snap会重新编译依赖库吗？—

**Comment by Iceyer** [comment]
> 我的做法是通过宏 liu-xiao-guo/deepin-voice-recorder

所以snap打包时不会重新编译dtkcore/dtkwidget这样的依赖库吗？

**Comment by liu-xiao-guo** [comment]
我的印象中，应该没有！ 

    On Friday, July 28, 2017 7:55 PM, Iceyer <notifications@github.com> wrote:
 

 
我的做法是通过宏 liu-xiao-guo/deepin-voice-recorder
所以snap打包时不会重新编译dtkcore/dtkwidget这样的依赖库吗？—

**Comment by Iceyer** [comment]
@liu-xiao-guo 已经在Dtk底层实现对snap路径转换的支持，应用部分代码只要在main函数入库添加下面代码就能自动用SNAP环境变量来代替QStandardPaths获得系统相关路径了。

`
#ifdef SNAP_APP
    DStandardPaths::setMode(DStandardPaths::Snap);
#endif
`

相关的CL见：

https://cr.deepin.io/#/c/25104/
https://cr.deepin.io/#/c/25107/
https://cr.deepin.io/#/c/25108/

**Comment by liu-xiao-guo** [comment]
我觉得你这种办法也是可以的 ：) 

    On Sunday, July 30, 2017 12:13 AM, Iceyer <notifications@github.com> wrote:
 

 @liu-xiao-guo 已经在Dtk底层实现对snap路径转换的支持，应用部分代码只要在main函数入库添加下面代码就能自动用SNAP环境变量来代替QStandardPaths获得系统相关路径了。#ifdef SNAP_APP DStandardPaths::setMode(DStandardPaths::Snap); #endif相关的CL见：https://cr.deepin.io/#/c/25104/
https://cr.deepin.io/#/c/25107/
https://cr.deepin.io/#/c/25108/—

**Pull request closed without merging**
