### PR TITLE
fix: 添加音乐按钮控件需要更新

### PR DESCRIPTION
**Pull request by wyu71**
更新添加音乐按钮控件

Log: 更新添加音乐按钮控件
Bug: https://pms.uniontech.com/bug-view-155749.html
/review @lzwind @myk1343 @feeengli @hundundadi

### CODE REVIEW

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
