### PR TITLE
fix: 播放列表拖拽滚动

### PR DESCRIPTION
**Pull request by feeengli**
播放列表添加拖拽滚动功能，删除歌曲提示窗口显示问题修复

Log: 播放列表添加拖拽滚动功能，删除歌曲提示窗口显示问题修复

Bug: https://pms.uniontech.com/bug-view-165957.html
     https://pms.uniontech.com/bug-view-185583.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
