### PR TITLE
chore: use GNUInstallDirs in CmakeLists

### PR DESCRIPTION
**Pull request by wineee**
Log: use GNUInstallDirs in CmakeLists

https://github.com/linuxdeepin/developer-center/issues/3167

### CODE REVIEW

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Comment by wineee** [comment]
需要 rebase

**Comment by wineee** [comment]
使用 https://github.com/linuxdeepin/deepin-music/pull/376 代替

**Pull request closed without merging**
