### PR TITLE
fix: 右键菜单排序、进度条、缺省页bug修复

### PR DESCRIPTION
**Pull request by feeengli**
右键菜单排序、进度条、缺省页bug修复

Log: 右键菜单排序、进度条、缺省页bug修复

Bug: https://pms.uniontech.com/bug-view-177301.html
     https://pms.uniontech.com/bug-view-176575.html
     https://pms.uniontech.com/bug-view-168521.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
