### PR TITLE
fix: 深色模式下专辑背景页歌曲名未匹配深色状态

### PR DESCRIPTION
**Pull request by wyu71**
深色模式下专辑背景页歌曲名匹配深色状态

Log: 深色模式下专辑背景页显示正常
Bug: https://pms.uniontech.com/bug-view-155757.html
/review @lzwind @myk1343 @hundundadi @feeengli

### CODE REVIEW

**Review by hundundadi — COMMENTED** [review]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by myk1343** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by feeengli** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by HeeMingYang — APPROVED** [review]
/+1

**Pull request merged**
