### PR TITLE
fix: 修复关闭提示窗口无法选择bug

### PR DESCRIPTION
**Pull request by feeengli**
修复关闭提示窗口无法选择bug

Log: 修复关闭提示窗口无法选择bug

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by wyu71 — APPROVED** [review]
/+1

**Pull request merged**
