### PR TITLE
fix: 设置界面背景颜色不随主题变化

### PR DESCRIPTION
**Pull request by feeengli**
修复设置界面背景颜色问题

Log: 修复设置界面背景颜色问题

Bug: https://pms.uniontech.com/bug-view-198891.html

### CODE REVIEW

**Comment by hundundadi** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Comment by jeffshuai** [comment]
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

**Review by lzwind — APPROVED** [review]
/+1

**Review by lzwind — APPROVED** [review]
/+1

**Pull request merged**
